In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

# Load the raw dataset
df = pd.read_csv("../data/raw/housing_raw.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()
print("Price column data type:")
print(df["PRICE"].dtype)

print("\nPrice summary:")
print(df["PRICE"].describe())

print("\nFirst 20 price values:")
print(df["PRICE"].head(20).to_list())

print("\nMissing prices:")
print(df["PRICE"].isna().sum())

Dataset loaded successfully!
Rows: 10704
Columns: 67
Price column data type:
str

Price summary:
count     10704
unique     1090
top        2 Cr
freq        178
Name: PRICE, dtype: object

First 20 price values:
['2.63 Cr', '3.6 Cr', '85,000', '3.85 Cr', '40,000', '1.95 Cr', '45,000', '1.62 Cr', '2.17 Cr', '2.2 Cr', '4.16 Cr', '7.5 Cr', '1.6 Cr', '70,000', '3.5 Cr', '2.58 Cr', '4.5 Cr', '1.55 Cr', '1.9 Cr', '1.9 Cr']

Missing prices:
0

C:\Users\hp\AppData\Local\Temp\ipykernel_18892\3475759534.py:6: DtypeWarning: Columns (66: FURNISHING_ATTRIBUTES) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/housing_raw.csv")

In [7]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}: {df[col].nunique()} unique")
    print(df[col].value_counts().head(8))

C:\Users\hp\AppData\Local\Temp\ipykernel_18892\2853646190.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

PROP_ID: 10704 unique
PROP_ID
O71585872    1
T71585466    1
D71549524    1
I71493958    1
H71479412    1
X71361930    1
Y71474260    1
N71483500    1
Name: count, dtype: int64

PHOTO_URL: 8830 unique
PHOTO_URL
https://static.99acres.com/images/under_screening_image.png                  35
https://mediacdn.99acres.com/media1/22409/13/448193438T-1695986883020.jpg     1
https://mediacdn.99acres.com/media1/22425/6/448506698T-1696148859724.jpg      1
https://mediacdn.99acres.com/media1/22386/13/447733494T-1695803391540.jpg     1
https://mediacdn.99acres.com/media1/22353/14/447074438T-1695463519193.jpg     1
https://mediacdn.99acres.com/media1/22352/4/447044532T-1695457324740.jpg      1
https://mediacdn.99acres.com/media1/22352/4/447044442T-1695457319627.jpg      1
https://mediacdn.99acres.com/media1/22351/18/447038984T-1695455515851.jpg     1
Name: count, dtype: int64

MEDIUM_PHOTO_URL: 8830 unique
MEDIUM_PHOTO_URL
https://static.99acres.com/images/under_screening_image.png                  35
https://mediacdn.99acres.com/media1/22409/13/448193438M-1695986883166.jpg     1
https://mediacdn.99acres.com/media1/22425/6/448506698M-1696148859950.jpg      1
https://mediacdn.99acres.com/media1/22386/13/447733494M-1695803391707.jpg     1
https://mediacdn.99acres.com/media1/22353/14/447074438M-1695463519524.jpg     1
https://mediacdn.99acres.com/media1/22352/4/447044532M-1695457325050.jpg      1
https://mediacdn.99acres.com/media1/22352/4/447044442M-1695457319950.jpg      1
https://mediacdn.99acres.com/media1/22351/18/447038984M-1695455516190.jpg     1
Name: count, dtype: int64

PREFERENCE: 2 unique
PREFERENCE
S    10155
R      549
Name: count, dtype: int64

DESCRIPTION: 9846 unique
DESCRIPTION
Very nicely built up ultra luxury builder floor with excellent interiors done with natural sunlight, all wardrobes are of ceiling hight, hettich modular kitchen, luxury washrooms with jaquar sanitary fittings wooden flooring in master bedroom, video door phone with electronic lock on the main gate and staircase gate, full length balcony with upvc windows, reserved car parking for visitors as well. This property offers a chance to witness to calm and reposed lifestyle amongst lush greenery . Walkin distance to huda market, swiss cottage school and manipal hospital.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     51
Ultra luxury floor located in a gated community with all modern amenities like modular kitchen, ceiling hight almirahs in all bed rooms, big size upvc windows for natural light, jaquar sanitary in all washrooms, modern architectural front elevation reserved car parking for all floor owners, cctv camera in stilt parking, video door phone with electronic lock for personal security sperate water storage tank.Walk in distance to the sector huda market and 2 mins drive to school and hospital.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   46
Good value, good property, and good location, best floor, best price and best facing\nAnd nearby school hospital parks gym and club, food corner etc...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        38
The happiness of living in the midst of the city, the convenience of having surrounded by life simplifying amenities. The satisfaction of enjoying a secure and peaceful lifestyle with the ones you love. This is developed with a single minded objective of giving you a happy lifestyle in a clean green surrounding.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      31
This property is very good becouse of itsattrective location and its enviroanment frindly , and all good schools and college are there and shoping mall are also there and convence is also and connectivity is very good                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      29
M3m crown\nM3m crown sector 111 gurgaon - Where luxury meets comfort! M3m crown is a new super luxury residential development by m3m group. This project is rera approved.The project provides luxurious apartments. The project is situated in sector 111, dwarka expressway gurgaon. For the one who lives an imperial life. There would never be a need to travel far in search of happiness because there are so many top amenities and facilities nearby. \nThis time the floor plans maximize the use of floor space giving into your every fancy rooms. \nEverything at the m3m crown apartments is designed around greenery for your better & healthy lifestyle.\nA happy & peaceful living starts when the people who stay in the home are happy and the neighborhood is also peaceful. But in todays hectic world. Keeping everyone happy is a hard task. But a few criteria and thoughtfulness can make that feasible living in sector 111, dwarka expressway, gurgaon.\nCrafted for people who are looking for a high standard of living far above the ordinary, this luxurious development brings together the luxury that nature and m3m crown.\n\nAmenities \nJogging track \nBasketball\nChildrens play area\nPool\nTennis\nAmphitheatre\nHealth club\nPlaza\nEasy access to malls, schools, and healthcare facilities\nApartments specification\nLiving room/dining/lobby/ family room\n Vitrified tiles\n Plaster with acrylic emulsion\n Entrance door  hardwood frames with elegant hardwood door\n Modular switches\nBalconies/terraces -\n Anti-Skid tiles\n Plaster with weatherproof raised paint\n Weatherproof paint\n Modular switches\nMaster bedroom -\n Laminated wooden flooring\n Plaster with acrylic emulsion\n Modular switches\nOther bedroom(s)\n Laminated wooden flooring\n Plaster with acrylic emulsion\nOther amenities -\n Reserved car park\n 5 kva/apartment power back-Up\n Centralized sewage treatment plant\n Perimeter security\nKitchen -\n Plaster with acrylic emulsion\n Granite countertop\n Single drainboard stainless steel sink with cp fittings\n Modular kitchen\n Modular switches\n\nEducational institute \nSwiss cottage school (2.1 km)\nMount school (1.1 km)\nRed roses public school (1.8 km)\nHe maurya school (2.0 km)\nDpsg (0.9 km)\n\nTransportation advantages\nDwarka metro station (3.8 km)\nGurgaon railway station (4.6 km)\n\n\nCommercial hub\nGoogle signature tower (7.5 km)\nSpaze itech park (12.6 km)\nUniversal business park (14.0 km)\n\nLocation advantages\n Ambience mall - 11.4 km\n Udyog vihar ph-2 - 10 km\n Igi airport - 11.4 km\n Metro station - 6.2 km\n Indira gandhi hospital - 10 km\n Swiss cottage school - 2.9 km\n Northcap university - 4.6 km\n\nEdc, idc, plc & other charges as applicable.    14

In [10]:
from pathlib import Path
import pandas as pd

# --------------------------------------------------
# 1. Load the original dataset
# --------------------------------------------------

project_root = Path("..")
data_path = project_root / "data" / "raw" / "housing_raw.csv"

df = pd.read_csv(data_path, low_memory=False)

print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# --------------------------------------------------
# 2. Describe the dataset columns
# --------------------------------------------------

column_info = {
    "PROP_ID": (
        "Unique property identifier",
        "identifier",
        "Not applicable",
        "Not normally used as a prediction feature"
    ),
    "PRICE": (
        "Listed property price",
        "text/numeric",
        "INR; verify units and transaction type",
        "Candidate target; raw values may contain Cr, lakh, or commas"
    ),
    "MIN_PRICE": (
        "Minimum listed price, if applicable",
        "text/numeric",
        "Verify from source",
        "Check meaning and consistency with PRICE"
    ),
    "MAX_PRICE": (
        "Maximum listed price, if applicable",
        "text/numeric",
        "Verify from source",
        "Check meaning and consistency with PRICE"
    ),
    "PRICE_PER_UNIT_AREA": (
        "Price per unit of property area",
        "text/numeric",
        "Verify from source",
        "Check units before using"
    ),
    "PRICE_SQFT": (
        "Price per square foot",
        "text/numeric",
        "INR/sqft, subject to verification",
        "Potentially derived from price and area; check for target leakage"
    ),
    "PROPERTY_TYPE": (
        "Type or category of property",
        "categorical",
        "Not applicable",
        "Potential prediction feature"
    ),
    "CITY": (
        "City associated with the property",
        "categorical",
        "Not applicable",
        "Verify geographic coverage from actual values"
    ),
    "LOCALITY": (
        "Locality or neighbourhood of the property",
        "categorical/text",
        "Not applicable",
        "May help represent location"
    ),
    "LOCALITY_WO_CITY": (
        "Locality name without the city name",
        "categorical/text",
        "Not applicable",
        "Check overlap with LOCALITY"
    ),
    "TRANSACT_TYPE": (
        "Transaction category",
        "categorical",
        "Not applicable",
        "Inspect values to distinguish sale, rent, and other listings"
    ),
    "PREFERENCE": (
        "Listing preference or category",
        "categorical",
        "Not applicable",
        "Meaning should be verified from source documentation"
    ),
    "OWNTYPE": (
        "Property ownership category",
        "categorical",
        "Not applicable",
        "Verify category definitions"
    ),
    "BEDROOM_NUM": (
        "Number of bedrooms",
        "numeric",
        "count",
        "Potential prediction feature"
    ),
    "BATHROOM_NUM": (
        "Number of bathrooms",
        "numeric",
        "count",
        "Potential prediction feature if present"
    ),
    "BALCONY_NUM": (
        "Number of balconies",
        "numeric",
        "count",
        "Potential prediction feature if present"
    ),
    "AREA": (
        "Listed property area",
        "text/numeric",
        "Verify from source",
        "Inspect for ranges and inconsistent formats"
    ),
    "CARPET_SQFT": (
        "Carpet area",
        "numeric/text",
        "square feet",
        "Check missing values and units"
    ),
    "BUILTUP_SQFT": (
        "Built-up area",
        "numeric/text",
        "square feet",
        "Check missing values and units"
    ),
    "SUPERBUILTUP_SQFT": (
        "Super built-up area",
        "numeric/text",
        "square feet",
        "Check missing values and units"
    ),
    "SUPER_SQFT": (
        "Super area measurement",
        "numeric/text",
        "square feet, subject to verification",
        "Check whether this duplicates another area column"
    ),
    "MIN_AREA_SQFT": (
        "Minimum listed area",
        "numeric/text",
        "square feet",
        "May be part of an area range"
    ),
    "MAX_AREA_SQFT": (
        "Maximum listed area",
        "numeric/text",
        "square feet",
        "May be part of an area range"
    ),
    "FURNISH": (
        "Furnishing category",
        "categorical",
        "Not applicable",
        "Verify category values"
    ),
    "FACING": (
        "Direction the property faces",
        "categorical",
        "Not applicable",
        "Potential prediction feature"
    ),
    "AGE": (
        "Property age or age category",
        "numeric/categorical",
        "Years or category; verify from source",
        "Inspect format before converting"
    ),
    "FLOOR_NUM": (
        "Floor on which the property is located",
        "numeric/text",
        "floor number",
        "Inspect non-numeric values"
    ),
    "TOTAL_FLOOR": (
        "Total number of floors in the building",
        "numeric/text",
        "count",
        "Potential prediction feature"
    ),
    "FEATURES": (
        "Property features or facilities",
        "text",
        "Not applicable",
        "May contain multiple features in one field"
    ),
    "AMENITIES": (
        "Amenities associated with the property",
        "text",
        "Not applicable",
        "May be useful for feature engineering"
    ),
    "TOP_USPS": (
        "Highlighted property selling points",
        "text",
        "Not applicable",
        "May contain multiple values"
    ),
    "TOTAL_LANDMARK_COUNT": (
        "Number of landmarks recorded for the property",
        "numeric",
        "count",
        "Verify how landmarks were counted"
    ),
    "FORMATTED_LANDMARK_DETAILS": (
        "Formatted information about nearby landmarks",
        "text",
        "Not applicable",
        "Inspect whether distances or landmark categories are available"
    ),
    "MAP_DETAILS": (
        "Map-related property information",
        "text/structured",
        "Not applicable",
        "Inspect before extracting location features"
    ),
    "location": (
        "Location-related information",
        "text/structured",
        "Not applicable",
        "Inspect format; may contain useful geographic information"
    ),
    "CITY_ID": (
        "Identifier associated with the city",
        "identifier",
        "Not applicable",
        "May duplicate information in CITY"
    ),
    "BUILDING_ID": (
        "Identifier associated with the building",
        "identifier",
        "Not applicable",
        "Not normally a direct prediction feature"
    ),
    "SOCIETY_NAME": (
        "Name of the residential society",
        "text",
        "Not applicable",
        "May contain missing values or high-cardinality categories"
    ),
    "BUILDING_NAME": (
        "Name of the building",
        "text",
        "Not applicable",
        "May contain high-cardinality values"
    ),
    "DESCRIPTION": (
        "Textual description of the property",
        "text",
        "Not applicable",
        "Unstructured text"
    ),
    "PROP_NAME": (
        "Property name",
        "text",
        "Not applicable",
        "Check overlap with other name fields"
    ),
    "PROP_HEADING": (
        "Property listing heading",
        "text",
        "Unstructured text"
    ),
    "PROP_DETAILS_URL": (
        "URL for property details",
        "text/URL",
        "Not applicable",
        "Source listing reference"
    ),
    "PHOTO_URL": (
        "URL for the property's photo",
        "text/URL",
        "Not applicable",
        "Image reference, not a numeric feature"
    ),
    "MEDIUM_PHOTO_URL": (
        "URL for a medium-sized property photo",
        "text/URL",
        "Not applicable",
        "Image reference"
    ),
    "PROPERTY_IMAGES": (
        "Property image information",
        "text/structured",
        "Not applicable",
        "May contain multiple image references"
    ),
    "THUMBNAIL_IMAGES": (
        "Thumbnail image information",
        "text/structured",
        "Not applicable",
        "May contain multiple image references"
    ),
    "REGISTER_DATE": (
        "Property registration date recorded in the dataset",
        "date/text",
        "Date",
        "Verify date format and meaning"
    ),
    "POSTING_DATE": (
        "Date the listing was posted",
        "date/text",
        "Date",
        "May help identify the dataset's time coverage"
    ),
    "UPDATE_DATE": (
        "Date the listing was updated",
        "date/text",
        "Date",
        "May help identify the dataset's time coverage"
    ),
    "EXPIRY_DATE": (
        "Listing expiry date",
        "date/text",
        "Date",
        "Verify meaning and availability"
    ),
    "FURNISHING_ATTRIBUTES": (
        "Detailed furnishing attributes",
        "text/structured",
        "Not applicable",
        "May contain mixed data types"
    ),
    "COMMON_FURNISHING_ATTRIBUTES": (
        "Common furnishing attributes",
        "text/structured",
        "Not applicable",
        "May contain multiple values"
    ),
    "QUALITY_SCORE": (
        "Quality score associated with the listing",
        "numeric",
        "Score; verify scale",
        "Check how the score was calculated"
    ),
    "BROKERAGE": (
        "Brokerage-related listing information",
        "text/numeric",
        "Verify from source",
        "Check units and meaning"
    ),
    "CONTACT_NAME": (
        "Name of the listing contact",
        "text",
        "Not applicable",
        "Personal/contact information; exclude from prediction features"
    ),
    "CONTACT_COMPANY_NAME": (
        "Company name associated with the contact",
        "text",
        "Not applicable",
        "Check relevance before using"
    ),
    "DEALER_PHOTO_URL": (
        "URL for the dealer's photo",
        "text/URL",
        "Not applicable",
        "Not normally a prediction feature"
    ),
    "metadata": (
        "Additional metadata",
        "text/structured",
        "Not applicable",
        "Inspect contents before using"
    ),
    "profile": (
        "Profile-related listing information",
        "text/structured",
        "Not applicable",
        "Meaning should be verified"
    ),
    "xid": (
        "External or source-specific identifier",
        "identifier",
        "Not applicable",
        "Not normally a direct prediction feature"
    ),
    "CLASS": (
        "Source-specific property classification",
        "categorical/text",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "CLASS_HEADING": (
        "Heading associated with the property classification",
        "text",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "CLASS_LABEL": (
        "Label associated with the property classification",
        "categorical/text",
        "Not applicable",
        "Verify category definitions"
    ),
    "SECONDARY_TAGS": (
        "Additional tags associated with the listing",
        "text/structured",
        "Not applicable",
        "May contain multiple categories"
    ),
    "GROUP_NAME": (
        "Group name associated with the listing",
        "text",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "LISTING": (
        "Listing-related information or category",
        "text/categorical",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "RES_COM": (
        "Residential/commercial classification or indicator",
        "categorical/text",
        "Not applicable",
        "Verify actual values and meaning"
    ),
    "PROPERTY_NUMBER": (
        "Property number or source-specific identifier",
        "text/identifier",
        "Not applicable",
        "Not normally a direct prediction feature"
    ),
    "MIN_PRICE": (
        "Minimum price associated with a listing",
        "text/numeric",
        "Verify from source",
        "Check for overlap with PRICE"
    ),
    "MAX_PRICE": (
        "Maximum price associated with a listing",
        "text/numeric",
        "Verify from source",
        "Check for overlap with PRICE"
    ),
}



# --------------------------------------------------
# 3. Generate the data dictionary
# --------------------------------------------------

dictionary_rows = []

for col in df.columns:

    # Default information for columns not documented yet
    default_info = (
        "Meaning not yet verified",
        str(df[col].dtype),
        "Not verified",
        "Inspect sample values and source documentation"
    )

    info = column_info.get(col, default_info)

    # Fix entries that do not contain exactly four values
    if not isinstance(info, (tuple, list)) or len(info) != 4:
        print(
            f"Warning: Invalid dictionary entry for '{col}'. "
            f"Using default information."
        )
        info = default_info

    meaning, data_type, unit, notes = info

    # Calculate missing percentage
    missing_pct = df[col].isna().mean() * 100

    # Record actual pandas data type
    actual_dtype = str(df[col].dtype)
    notes = f"{notes}; pandas dtype: {actual_dtype}"

    # Escape special characters for Markdown
    def escape_markdown(value):
        return (
            str(value)
            .replace("|", "\\|")
            .replace("\n", " ")
        )

    dictionary_rows.append({
        "Column": escape_markdown(col),
        "Meaning": escape_markdown(meaning),
        "Type": escape_markdown(data_type),
        "Unit": escape_markdown(unit),
        "Missing %": f"{missing_pct:.2f}%",
        "Notes": escape_markdown(notes)
    })


# Convert to DataFrame
dictionary = pd.DataFrame(dictionary_rows)


# --------------------------------------------------
# 4. Save the Markdown file
# --------------------------------------------------

project_root = Path("..")

reports_dir = project_root / "reports"
reports_dir.mkdir(parents=True, exist_ok=True)

dictionary_path = reports_dir / "data_dictionary.md"


# Create Markdown content
markdown = f"""# Data Dictionary

## Dataset Overview

- **Dataset file:** `data/raw/housing_raw.csv`
- **Number of rows:** {df.shape[0]:,}
- **Number of columns:** {df.shape[1]}
- **Purpose:** Document the fields in the raw real-estate dataset.
- **Note:** Column meanings and units marked for verification must be
  confirmed against the original dataset documentation.

## Column Descriptions

{dictionary.to_markdown(index=False)}

## Data Quality Notes

- The original dataset is preserved in `data/raw/`.
- Missing percentages are calculated from the raw data before cleaning.
- Data types represent the current pandas representation of each column.
- Price units and transaction categories must be verified before
  preparing the prediction target.
- Listed prices should not automatically be interpreted as completed
  sale prices.
"""

# Write file
dictionary_path.write_text(markdown, encoding="utf-8")


# --------------------------------------------------
# 5. Confirm successful creation
# --------------------------------------------------

print("\nData dictionary created successfully!")
print("File location:", dictionary_path.resolve())
print("Columns documented:", len(dictionary))
print("File size:", dictionary_path.stat().st_size, "bytes")

print("\nFirst five entries:")
display(dictionary.head())

Dataset loaded successfully.
Rows: 10704
Columns: 67
Warning: Invalid dictionary entry for 'PROP_HEADING'. Using default information.

Data dictionary created successfully!
File location: D:\real-estate-price-prediction\reports\data_dictionary.md
Columns documented: 67
File size: 18454 bytes

First five entries:

,Column,Meaning,Type,Unit,Missing %,Notes
0,PROP_ID,Unique property identifier,identifier,Not applicable,0.00%,Not normally used as a prediction feature; pan...
1,PHOTO_URL,URL for the property's photo,text/URL,Not applicable,17.19%,"Image reference, not a numeric feature; pandas..."
2,MEDIUM_PHOTO_URL,URL for a medium-sized property photo,text/URL,Not applicable,17.19%,Image reference; pandas dtype: str
3,PREFERENCE,Listing preference or category,categorical,Not applicable,0.00%,Meaning should be verified from source documen...
4,DESCRIPTION,Textual description of the property,text,Not applicable,0.00%,Unstructured text; pandas dtype: str

In [11]:
# Check relevant columns
print("Location-related columns:")

for col in df.columns:
    if any(word in col.lower() for word in [
        "location", "locality", "latitude", "longitude",
        "latitude", "longitude", "lat", "lon", "map"
    ]):
        print(col)

print("\nNumber of unique localities:")
if "LOCALITY" in df.columns:
    print(df["LOCALITY"].nunique())

print("\nSample LOCALITY values:")
if "LOCALITY" in df.columns:
    print(df["LOCALITY"].dropna().head(10).to_list())

print("\nSample location values:")
if "location" in df.columns:
    print(df["location"].dropna().head(5).to_list())

Location-related columns:
LOCALITY
MAP_DETAILS
LOCALITY_WO_CITY
location

Number of unique localities:
231

Sample LOCALITY values:
['Sector 84 Gurgaon', 'Sector 81 Gurgaon', 'Sector 66 Gurgaon', 'Sector 112 Gurgaon', 'Sector 104 Gurgaon', 'Sector 104 Gurgaon', 'Sector 104 Gurgaon', 'Sector 74 Gurgaon', 'Sector 108 Gurgaon', 'Sector 102 Gurgaon']

Sample location values:
["{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDING_ID': '10532', 'BUILDING_NAME': 'Alpha Corp GurgaonOne 84', 'SOCIETY_NAME': 'Alpha Corp GurgaonOne 84', 'LOCALITY_ID': '7580', 'LOCALITY_NAME': 'Sector 84 Gurgaon'}", "{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDING_ID': '12704', 'BUILDING_NAME': 'DLF The Ultima', 'SOCIETY_NAME': 'DLF The Ultima', 'LOCALITY_ID': '7870', 'LOCALITY_NAME': 'Sector 81 Gurgaon', 'ADDRESS': '7th Floor'}", "{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDING_ID': '3252', 'BUILDING_NAME': 'Emaar MGF The Palm Drive', 'SOCIETY_NAME': 'Emaar MGF The Palm Drive', 'LOCALITY_ID': '7488', 'LOCALITY_NAME': 'Sector 66 Gurgaon', 'ADDRESS': '703'}", "{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDING_ID': '9772', 'BUILDING_NAME': 'Experion Windchants', 'SOCIETY_NAME': 'Experion Windchants', 'LOCALITY_ID': '8877', 'LOCALITY_NAME': 'Sector 112 Gurgaon'}", "{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDING_ID': '41176', 'BUILDING_NAME': 'ATS Triumph', 'SOCIETY_NAME': 'ATS Triumph', 'LOCALITY_ID': '9084', 'LOCALITY_NAME': 'Sector 104 Gurgaon'}"]

In [ ]:
from pathlib import Path
import pandas as pd

# --------------------------------------------------
# 1. Load the original dataset
# --------------------------------------------------

project_root = Path("..")
data_path = project_root / "data" / "raw" / "housing_raw.csv"

df = pd.read_csv(data_path, low_memory=False)

print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])


# --------------------------------------------------
# 2. Describe the dataset columns
# --------------------------------------------------

column_info = {
    "PROP_ID": (
        "Unique property identifier",
        "identifier",
        "Not applicable",
        "Not normally used as a prediction feature"
    ),
    "PRICE": (
        "Listed property price",
        "text/numeric",
        "INR; verify units and transaction type",
        "Candidate target; raw values may contain Cr, lakh, or commas"
    ),
    "MIN_PRICE": (
        "Minimum listed price, if applicable",
        "text/numeric",
        "Verify from source",
        "Check meaning and consistency with PRICE"
    ),
    "MAX_PRICE": (
        "Maximum listed price, if applicable",
        "text/numeric",
        "Verify from source",
        "Check meaning and consistency with PRICE"
    ),
    "PRICE_PER_UNIT_AREA": (
        "Price per unit of property area",
        "text/numeric",
        "Verify from source",
        "Check units before using"
    ),
    "PRICE_SQFT": (
        "Price per square foot",
        "text/numeric",
        "INR/sqft, subject to verification",
        "Potentially derived from price and area; check for target leakage"
    ),
    "PROPERTY_TYPE": (
        "Type or category of property",
        "categorical",
        "Not applicable",
        "Potential prediction feature"
    ),
    "CITY": (
        "City associated with the property",
        "categorical",
        "Not applicable",
        "Verify geographic coverage from actual values"
    ),
    "LOCALITY": (
        "Locality or neighbourhood of the property",
        "categorical/text",
        "Not applicable",
        "May help represent location"
    ),
    "LOCALITY_WO_CITY": (
        "Locality name without the city name",
        "categorical/text",
        "Not applicable",
        "Check overlap with LOCALITY"
    ),
    "TRANSACT_TYPE": (
        "Transaction category",
        "categorical",
        "Not applicable",
        "Inspect values to distinguish sale, rent, and other listings"
    ),
    "PREFERENCE": (
        "Listing preference or category",
        "categorical",
        "Not applicable",
        "Meaning should be verified from source documentation"
    ),
    "OWNTYPE": (
        "Property ownership category",
        "categorical",
        "Not applicable",
        "Verify category definitions"
    ),
    "BEDROOM_NUM": (
        "Number of bedrooms",
        "numeric",
        "count",
        "Potential prediction feature"
    ),
    "BATHROOM_NUM": (
        "Number of bathrooms",
        "numeric",
        "count",
        "Potential prediction feature if present"
    ),
    "BALCONY_NUM": (
        "Number of balconies",
        "numeric",
        "count",
        "Potential prediction feature if present"
    ),
    "AREA": (
        "Listed property area",
        "text/numeric",
        "Verify from source",
        "Inspect for ranges and inconsistent formats"
    ),
    "CARPET_SQFT": (
        "Carpet area",
        "numeric/text",
        "square feet",
        "Check missing values and units"
    ),
    "BUILTUP_SQFT": (
        "Built-up area",
        "numeric/text",
        "square feet",
        "Check missing values and units"
    ),
    "SUPERBUILTUP_SQFT": (
        "Super built-up area",
        "numeric/text",
        "square feet",
        "Check missing values and units"
    ),
    "SUPER_SQFT": (
        "Super area measurement",
        "numeric/text",
        "square feet, subject to verification",
        "Check whether this duplicates another area column"
    ),
    "MIN_AREA_SQFT": (
        "Minimum listed area",
        "numeric/text",
        "square feet",
        "May be part of an area range"
    ),
    "MAX_AREA_SQFT": (
        "Maximum listed area",
        "numeric/text",
        "square feet",
        "May be part of an area range"
    ),
    "FURNISH": (
        "Furnishing category",
        "categorical",
        "Not applicable",
        "Verify category values"
    ),
    "FACING": (
        "Direction the property faces",
        "categorical",
        "Not applicable",
        "Potential prediction feature"
    ),
    "AGE": (
        "Property age or age category",
        "numeric/categorical",
        "Years or category; verify from source",
        "Inspect format before converting"
    ),
    "FLOOR_NUM": (
        "Floor on which the property is located",
        "numeric/text",
        "floor number",
        "Inspect non-numeric values"
    ),
    "TOTAL_FLOOR": (
        "Total number of floors in the building",
        "numeric/text",
        "count",
        "Potential prediction feature"
    ),
    "FEATURES": (
        "Property features or facilities",
        "text",
        "Not applicable",
        "May contain multiple features in one field"
    ),
    "AMENITIES": (
        "Amenities associated with the property",
        "text",
        "Not applicable",
        "May be useful for feature engineering"
    ),
    "TOP_USPS": (
        "Highlighted property selling points",
        "text",
        "Not applicable",
        "May contain multiple values"
    ),
    "TOTAL_LANDMARK_COUNT": (
        "Number of landmarks recorded for the property",
        "numeric",
        "count",
        "Verify how landmarks were counted"
    ),
    "FORMATTED_LANDMARK_DETAILS": (
        "Formatted information about nearby landmarks",
        "text",
        "Not applicable",
        "Inspect whether distances or landmark categories are available"
    ),
    "MAP_DETAILS": (
        "Map-related property information",
        "text/structured",
        "Not applicable",
        "Inspect before extracting location features"
    ),
    "location": (
        "Location-related information",
        "text/structured",
        "Not applicable",
        "Inspect format; may contain useful geographic information"
    ),
    "CITY_ID": (
        "Identifier associated with the city",
        "identifier",
        "Not applicable",
        "May duplicate information in CITY"
    ),
    "BUILDING_ID": (
        "Identifier associated with the building",
        "identifier",
        "Not applicable",
        "Not normally a direct prediction feature"
    ),
    "SOCIETY_NAME": (
        "Name of the residential society",
        "text",
        "Not applicable",
        "May contain missing values or high-cardinality categories"
    ),
    "BUILDING_NAME": (
        "Name of the building",
        "text",
        "Not applicable",
        "May contain high-cardinality values"
    ),
    "DESCRIPTION": (
        "Textual description of the property",
        "text",
        "Not applicable",
        "Unstructured text"
    ),
    "PROP_NAME": (
        "Property name",
        "text",
        "Not applicable",
        "Check overlap with other name fields"
    ),
    "PROP_HEADING": (
        "Property listing heading",
        "text",
        "Unstructured text"
    ),
    "PROP_DETAILS_URL": (
        "URL for property details",
        "text/URL",
        "Not applicable",
        "Source listing reference"
    ),
    "PHOTO_URL": (
        "URL for the property's photo",
        "text/URL",
        "Not applicable",
        "Image reference, not a numeric feature"
    ),
    "MEDIUM_PHOTO_URL": (
        "URL for a medium-sized property photo",
        "text/URL",
        "Not applicable",
        "Image reference"
    ),
    "PROPERTY_IMAGES": (
        "Property image information",
        "text/structured",
        "Not applicable",
        "May contain multiple image references"
    ),
    "THUMBNAIL_IMAGES": (
        "Thumbnail image information",
        "text/structured",
        "Not applicable",
        "May contain multiple image references"
    ),
    "REGISTER_DATE": (
        "Property registration date recorded in the dataset",
        "date/text",
        "Date",
        "Verify date format and meaning"
    ),
    "POSTING_DATE": (
        "Date the listing was posted",
        "date/text",
        "Date",
        "May help identify the dataset's time coverage"
    ),
    "UPDATE_DATE": (
        "Date the listing was updated",
        "date/text",
        "Date",
        "May help identify the dataset's time coverage"
    ),
    "EXPIRY_DATE": (
        "Listing expiry date",
        "date/text",
        "Date",
        "Verify meaning and availability"
    ),
    "FURNISHING_ATTRIBUTES": (
        "Detailed furnishing attributes",
        "text/structured",
        "Not applicable",
        "May contain mixed data types"
    ),
    "COMMON_FURNISHING_ATTRIBUTES": (
        "Common furnishing attributes",
        "text/structured",
        "Not applicable",
        "May contain multiple values"
    ),
    "QUALITY_SCORE": (
        "Quality score associated with the listing",
        "numeric",
        "Score; verify scale",
        "Check how the score was calculated"
    ),
    "BROKERAGE": (
        "Brokerage-related listing information",
        "text/numeric",
        "Verify from source",
        "Check units and meaning"
    ),
    "CONTACT_NAME": (
        "Name of the listing contact",
        "text",
        "Not applicable",
        "Personal/contact information; exclude from prediction features"
    ),
    "CONTACT_COMPANY_NAME": (
        "Company name associated with the contact",
        "text",
        "Not applicable",
        "Check relevance before using"
    ),
    "DEALER_PHOTO_URL": (
        "URL for the dealer's photo",
        "text/URL",
        "Not applicable",
        "Not normally a prediction feature"
    ),
    "metadata": (
        "Additional metadata",
        "text/structured",
        "Not applicable",
        "Inspect contents before using"
    ),
    "profile": (
        "Profile-related listing information",
        "text/structured",
        "Not applicable",
        "Meaning should be verified"
    ),
    "xid": (
        "External or source-specific identifier",
        "identifier",
        "Not applicable",
        "Not normally a direct prediction feature"
    ),
    "CLASS": (
        "Source-specific property classification",
        "categorical/text",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "CLASS_HEADING": (
        "Heading associated with the property classification",
        "text",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "CLASS_LABEL": (
        "Label associated with the property classification",
        "categorical/text",
        "Not applicable",
        "Verify category definitions"
    ),
    "SECONDARY_TAGS": (
        "Additional tags associated with the listing",
        "text/structured",
        "Not applicable",
        "May contain multiple categories"
    ),
    "GROUP_NAME": (
        "Group name associated with the listing",
        "text",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "LISTING": (
        "Listing-related information or category",
        "text/categorical",
        "Not applicable",
        "Verify meaning from source documentation"
    ),
    "RES_COM": (
        "Residential/commercial classification or indicator",
        "categorical/text",
        "Not applicable",
        "Verify actual values and meaning"
    ),
    "PROPERTY_NUMBER": (
        "Property number or source-specific identifier",
        "text/identifier",
        "Not applicable",
        "Not normally a direct prediction feature"
    ),
    "MIN_PRICE": (
        "Minimum price associated with a listing",
        "text/numeric",
        "Verify from source",
        "Check for overlap with PRICE"
    ),
    "MAX_PRICE": (
        "Maximum price associated with a listing",
        "text/numeric",
        "Verify from source",
        "Check for overlap with PRICE"
    ),
}



# --------------------------------------------------
# 3. Generate the data dictionary
# --------------------------------------------------

dictionary_rows = []

for col in df.columns:

    # Default information for columns not documented yet
    default_info = (
        "Meaning not yet verified",
        str(df[col].dtype),
        "Not verified",
        "Inspect sample values and source documentation"
    )

    info = column_info.get(col, default_info)

    # Fix entries that do not contain exactly four values
    if not isinstance(info, (tuple, list)) or len(info) != 4:
        print(
            f"Warning: Invalid dictionary entry for '{col}'. "
            f"Using default information."
        )
        info = default_info

    meaning, data_type, unit, notes = info

    # Calculate missing percentage
    missing_pct = df[col].isna().mean() * 100

    # Record actual pandas data type
    actual_dtype = str(df[col].dtype)
    notes = f"{notes}; pandas dtype: {actual_dtype}"

    # Escape special characters for Markdown
    def escape_markdown(value):
        return (
            str(value)
            .replace("|", "\\|")
            .replace("\n", " ")
        )

    dictionary_rows.append({
        "Column": escape_markdown(col),
        "Meaning": escape_markdown(meaning),
        "Type": escape_markdown(data_type),
        "Unit": escape_markdown(unit),
        "Missing %": f"{missing_pct:.2f}%",
        "Notes": escape_markdown(notes)
    })


# Convert to DataFrame
dictionary = pd.DataFrame(dictionary_rows)


# --------------------------------------------------
# 4. Save the Markdown file
# --------------------------------------------------

project_root = Path("..")

reports_dir = project_root / "reports"
reports_dir.mkdir(parents=True, exist_ok=True)

dictionary_path = reports_dir / "data_dictionary.md"


# Create Markdown content
markdown = f"""# Data Dictionary

## Dataset Overview

- **Dataset file:** `data/raw/housing_raw.csv`
- **Number of rows:** {df.shape[0]:,}
- **Number of columns:** {df.shape[1]}
- **Purpose:** Document the fields in the raw real-estate dataset.
- **Note:** Column meanings and units marked for verification must be
  confirmed against the original dataset documentation.

## Column Descriptions

{dictionary.to_markdown(index=False)}

## Data Quality Notes

- The original dataset is preserved in `data/raw/`.
- Missing percentages are calculated from the raw data before cleaning.
- Data types represent the current pandas representation of each column.
- Price units and transaction categories must be verified before
  preparing the prediction target.
- Listed prices should not automatically be interpreted as completed
  sale prices.
"""

# Write file
dictionary_path.write_text(markdown, encoding="utf-8")


# --------------------------------------------------
# 5. Confirm successful creation
# --------------------------------------------------

print("\nData dictionary created successfully!")
print("File location:", dictionary_path.resolve())
print("Columns documented:", len(dictionary))
print("File size:", dictionary_path.stat().st_size, "bytes")

print("\nFirst five entries:")
display(dictionary.head())

Dataset loaded successfully.
Rows: 10704
Columns: 67
Warning: Invalid dictionary entry for 'PROP_HEADING'. Using default information.

Data dictionary created successfully!
File location: D:\real-estate-price-prediction\reports\data_dictionary.md
Columns documented: 67
File size: 18454 bytes

First five entries:

,Column,Meaning,Type,Unit,Missing %,Notes
0,PROP_ID,Unique property identifier,identifier,Not applicable,0.00%,Not normally used as a prediction feature; pan...
1,PHOTO_URL,URL for the property's photo,text/URL,Not applicable,17.19%,"Image reference, not a numeric feature; pandas..."
2,MEDIUM_PHOTO_URL,URL for a medium-sized property photo,text/URL,Not applicable,17.19%,Image reference; pandas dtype: str
3,PREFERENCE,Listing preference or category,categorical,Not applicable,0.00%,Meaning should be verified from source documen...
4,DESCRIPTION,Textual description of the property,text,Not applicable,0.00%,Unstructured text; pandas dtype: str

In [12]:
import pandas as pd
import json
import time
from pathlib import Path
from geopy.geocoders import Nominatim

In [13]:
locality_col = "LOCALITY"

print("Total property records:", len(df))
print("Unique localities:", df[locality_col].nunique())
print("Missing locality values:", df[locality_col].isna().sum())

Total property records: 10704
Unique localities: 231
Missing locality values: 0

In [18]:
from pathlib import Path
from geopy.geocoders import Nominatim

# Project directories
project_root = Path("..")
raw_dir = project_root / "data" / "raw"
raw_dir.mkdir(parents=True, exist_ok=True)

cache_path = raw_dir / "geocode_cache.json"

# Initialize geocoder
geolocator = Nominatim(
    user_agent="real_estate_price_prediction_college_project"
)

# Load previously cached coordinates
if cache_path.exists():
    with open(cache_path, "r", encoding="utf-8") as f:
        cache = json.load(f)
else:
    cache = {}

print("Cached locations:", len(cache))

Cached locations: 0

In [19]:
import json
import time

CITY = "Gurgaon, Haryana, India"

def geocode_locality(name):
    name = str(name).strip()

    if not name:
        return None

    # Reuse previously obtained coordinates
    if name in cache:
        return cache[name]

    try:
        result = geolocator.geocode(
            f"{name}, {CITY}",
            timeout=15
        )

        if result:
            coordinates = [
                result.latitude,
                result.longitude
            ]

            cache[name] = coordinates

        else:
            # Cache a not-found result to avoid repeating it
            cache[name] = None
            coordinates = None

        # Save after each completed request
        with open(cache_path, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2)

        # Respect the public service's request rate
        time.sleep(1.1)

        return coordinates

    except Exception as e:
        # Do not cache errors; they can be retried later
        print(f"Error geocoding '{name}': {e}")
        return None

In [20]:
print("Starting geocoding test...")

localities = (
    df[locality_col]
    .dropna()
    .astype(str)
    .str.strip()
)

localities = localities[localities.ne("")].unique()

print("Unique localities:", len(localities))
print("Already cached:", len(cache))

for locality in localities[:5]:
    print(f"\nLooking up: {locality}", flush=True)

    coordinates = geocode_locality(locality)

    print(f"Result: {coordinates}", flush=True)

print("\nGeocoding test finished.")

Starting geocoding test...
Unique localities: 231
Already cached: 0

Looking up: Sector 84 Gurgaon
Result: [28.4035469, 76.9677894]

Looking up: Sector 81 Gurgaon
Result: [28.3873647, 76.9475835]

Looking up: Sector 66 Gurgaon
Result: [28.3974292, 77.0538823]

Looking up: Sector 112 Gurgaon
Result: [28.5203402, 77.0188612]

Looking up: Sector 104 Gurgaon
Result: [28.4795324, 76.9937197]

Geocoding test finished.

In [21]:
# Geocode all unique localities

total = len(localities)

for i, locality in enumerate(localities, start=1):

    if locality in cache:
        continue

    print(f"[{i}/{total}] Geocoding: {locality}", flush=True)

    coordinates = geocode_locality(locality)

    print(f"    Coordinates: {coordinates}", flush=True)

print("\nGeocoding completed!")
print("Total localities:", total)
print("Cached results:", len(cache))
print("Successful results:", sum(v is not None for v in cache.values()))
print("Unsuccessful lookups:", sum(v is None for v in cache.values()))

[6/231] Geocoding: Sector 74 Gurgaon
    Coordinates: [28.4110081, 77.0101209]
[7/231] Geocoding: Sector 108 Gurgaon
    Coordinates: [28.5128994, 76.9823615]
[8/231] Geocoding: Sector 102 Gurgaon
    Coordinates: [28.4754872, 76.9711747]
[9/231] Geocoding: Sector 99 Gurgaon
    Coordinates: [28.4645549, 76.9628585]
[10/231] Geocoding: Sector 60 Gurgaon
    Coordinates: [28.3985617, 77.0978276]
[11/231] Geocoding: Sector 110 Gurgaon
    Coordinates: [28.5069625, 77.018321]
[12/231] Geocoding: Sector 109 Gurgaon
    Coordinates: [28.5109205, 77.0065956]
[13/231] Geocoding: Sector 65 Gurgaon
    Coordinates: [28.4030162, 77.0695893]
[14/231] Geocoding: Sector 37D Gurgaon
    Coordinates: [28.4480039, 76.9697682]
[15/231] Geocoding: Sector 113 Gurgaon
    Coordinates: [28.5286649, 77.0250282]
[16/231] Geocoding: Sector 111 Gurgaon
    Coordinates: [28.5222773, 77.0336203]
[17/231] Geocoding: Sector 61 Gurgaon
    Coordinates: [28.4110188, 77.0963685]
[18/231] Geocoding: Block B Sushant Lok Phase - 3
    Coordinates: None
[19/231] Geocoding: Sector 62 Gurgaon
    Coordinates: [28.407697, 77.0823781]
[20/231] Geocoding: South City 1
    Coordinates: [28.4188433, 77.0440293]
[21/231] Geocoding: Sector 57 Gurgaon
    Coordinates: [28.4232478, 77.0804487]
[22/231] Geocoding: Sector 59 Gurgaon
    Coordinates: [28.4030162, 77.1066682]
[23/231] Geocoding: Sector 37C Gurgaon
    Coordinates: [28.4489095, 76.9880502]
[24/231] Geocoding: Sector 53 Gurgaon
    Coordinates: [28.4487856, 77.0988212]
[25/231] Geocoding: Sector 28 Gurgaon
    Coordinates: [28.4794143, 77.0833588]
[26/231] Geocoding: Sector 67 Gurgaon
    Coordinates: [28.3864052, 77.0598046]
[27/231] Geocoding: Sector 54 Gurgaon
    Coordinates: [28.4409224, 77.1028638]
[28/231] Geocoding: Sector 106 Gurgaon
    Coordinates: [28.5060806, 76.9967796]
[29/231] Geocoding: DLF Phase 2
    Coordinates: [28.483901, 77.0846097]
[30/231] Geocoding: Sector 82 Gurgaon
    Coordinates: [28.3932827, 76.9545277]
[31/231] Geocoding: South City 2
    Coordinates: [28.4188806, 77.0439211]
[32/231] Geocoding: DLF Phase 5
    Coordinates: [28.503445, 77.0952048]
[33/231] Geocoding: DLF Phase 3
    Coordinates: [28.4919048, 77.0937804]
[34/231] Geocoding: Sector 42 Gurgaon
    Coordinates: [28.4487856, 77.0988212]
[35/231] Geocoding: Sector 55 Gurgaon
    Coordinates: [28.4274166, 77.1097538]
[36/231] Geocoding: Sector 48 Gurgaon
    Coordinates: [28.4104903, 77.0394627]
[37/231] Geocoding: Sector-33 Sohna
    Coordinates: [28.3241636, 77.0848644]
[38/231] Geocoding: Sector 90 Gurgaon
    Coordinates: [28.4069974, 76.9365562]
[39/231] Geocoding: Sector 103 Gurgaon
    Coordinates: [28.493087, 76.9866453]
[40/231] Geocoding: Block C, Sushant Lok Phase 1
    Coordinates: None
[41/231] Geocoding: Sector 63 Gurgaon
    Coordinates: [28.3964476, 77.086498]
[42/231] Geocoding: DLF Phase 1
    Coordinates: [28.4765171, 77.090194]
[43/231] Geocoding: Sector 107 Gurgaon
    Coordinates: [28.506941, 76.9752137]
[44/231] Geocoding: Sohna
    Coordinates: [28.3241636, 77.0848644]
[45/231] Geocoding: Malibu Town
    Coordinates: [28.4234344, 77.0468649]
[46/231] Geocoding: Sector 63A Gurgaon
    Coordinates: [28.3864052, 77.0598046]
[47/231] Geocoding: Uppals Southend
    Coordinates: None
[48/231] Geocoding: Sector 85 Gurgaon
    Coordinates: [28.3985762, 76.9547447]
[49/231] Geocoding: Sector-35 Sohna
    Coordinates: [28.3241636, 77.0848644]
[50/231] Geocoding: Sector 68 Gurgaon
    Coordinates: [28.388897, 77.0459859]
[51/231] Geocoding: Nirvana Country
    Coordinates: [28.4150509, 77.0642955]
[52/231] Geocoding: Sushant Lok Phase 1
    Coordinates: [28.4545693, 77.0826249]
[53/231] Geocoding: Sector 88A Gurgaon
    Coordinates: [28.4337898, 76.9539433]
[54/231] Geocoding: Sector 99A Gurgaon
    Coordinates: [28.4554059, 76.9510278]
[55/231] Geocoding: Rosewood
    Coordinates: [28.4102341, 77.0544854]
[56/231] Geocoding: Sector 50 Gurgaon
    Coordinates: [28.4268461, 77.0584252]
[57/231] Geocoding: Sector 36A Gurgaon
    Coordinates: [28.4202285, 76.9719998]
[58/231] Geocoding: Sector 88 Gurgaon
    Coordinates: [28.4219647, 76.9568078]
[59/231] Geocoding: Sector 89 Gurgaon
    Coordinates: [28.4184455, 76.9457567]
[60/231] Geocoding: Sector 110 A Gurgaon
    Coordinates: [28.5069625, 77.018321]
[61/231] Geocoding: machroli
    Coordinates: None
[62/231] Geocoding: Sector 51 Gurgaon
    Coordinates: [28.4287011, 77.0666877]
[63/231] Geocoding: Sector 31 Gurgaon
    Coordinates: [28.4540044, 77.0497179]
[64/231] Geocoding: Palam Vihar
    Coordinates: [28.4983353, 77.0203007]
[65/231] Geocoding: Sector 23 Gurgaon
    Coordinates: [28.510319, 77.0530094]
[66/231] Geocoding: New Palam Vihar Phase 2
    Coordinates: None
[67/231] Geocoding: Sector 46 Gurgaon
    Coordinates: [28.4268461, 77.0584252]
[68/231] Geocoding: Sector 45 Gurgaon
    Coordinates: [28.4449004, 77.0663545]
[69/231] Geocoding: New Palam Vihar
    Coordinates: [28.4868613, 77.019042]
[70/231] Geocoding: Sector 67A Gurgaon
    Coordinates: [28.3864052, 77.0598046]
[71/231] Geocoding: Sector 36 Sohna
    Coordinates: [28.4160012, 77.1085564]
[72/231] Geocoding: Sector 71 Gurgaon
    Coordinates: [28.3950557, 77.0314336]
[73/231] Geocoding: Sector 82A Gurgaon
    Coordinates: [28.3881583, 76.96273]
[74/231] Geocoding: Sector 14 Gurgaon
    Coordinates: [28.4741534, 77.047729]
[75/231] Geocoding: DLF Phase 4
    Coordinates: [28.4919048, 77.0937804]
[76/231] Geocoding: Sushant Lok Phase 3
    Coordinates: [28.464228, 77.076724]
[77/231] Geocoding: Sector 72 Gurgaon
    Coordinates: [28.3943815, 77.032363]
[78/231] Geocoding: Sector 3 Gurgaon
    Coordinates: [28.4944483, 77.0985008]
[79/231] Geocoding: Sector 49 Gurgaon
    Coordinates: [28.4127374, 77.0555164]
[80/231] Geocoding: Sector-4 Sohna
    Coordinates: [28.3241636, 77.0848644]
[81/231] Geocoding: Sector-2 Sohna
    Coordinates: [28.3241636, 77.0848644]
[82/231] Geocoding: Block C Palam Vihar
    Coordinates: [28.4829959, 77.0333555]
[83/231] Geocoding: Sector 70 Gurgaon
    Coordinates: [28.3947261, 77.0223138]
[84/231] Geocoding: Sector 88B Gurgaon
    Coordinates: [28.4420223, 76.9538495]
[85/231] Geocoding: Sector 92 Gurgaon
    Coordinates: [28.4089049, 76.9155232]
[86/231] Geocoding: Sector 69 Gurgaon
    Coordinates: [28.3960701, 77.0372311]
[87/231] Geocoding: Gwal Pahari
    Coordinates: [28.4326344, 77.1480585]
[88/231] Geocoding: C Block Sushant Lok Phase 1
    Coordinates: [28.4545693, 77.0826249]
[89/231] Geocoding: Sector 83 Gurgaon
    Coordinates: [28.3963578, 76.9654747]
[90/231] Geocoding: MG Road
    Coordinates: [28.4769607, 77.0662688]
[91/231] Geocoding: Sector 70A Gurgaon
    Coordinates: [28.3846684, 77.0220391]
[92/231] Geocoding: Sector 79 Gurgaon
    Coordinates: [28.3864052, 77.0598046]
[93/231] Geocoding: Sector 52 Gurgaon
    Coordinates: [28.4368166, 77.0795276]
[94/231] Geocoding: Sector 86 Gurgaon
    Coordinates: [28.3981205, 76.9411257]
[95/231] Geocoding: A Block Sushant Lok Phase 1
    Coordinates: None
[96/231] Geocoding: Sector 47 Gurgaon
    Coordinates: [28.4268461, 77.0584252]
[97/231] Geocoding: Sushant Lok Phase 2
    Coordinates: [28.464228, 77.076724]
[98/231] Geocoding: Sector 26 Gurgaon
    Coordinates: [28.4779375, 77.1032425]
[99/231] Geocoding: Sector 56 Gurgaon
    Coordinates: [28.4252244, 77.0992377]
[100/231] Geocoding: Sector 43 Gurgaon
    Coordinates: [28.4487856, 77.0988212]
[101/231] Geocoding: Ardee City
    Coordinates: [28.4410412, 77.0792079]
[102/231] Geocoding: Sector 27 Gurgaon
    Coordinates: [28.4654327, 77.0742802]
[103/231] Geocoding: Sector 89 A Gurgaon
    Coordinates: [28.4184455, 76.9457567]
[104/231] Geocoding: Sector 93 Gurgaon
    Coordinates: [28.4156048, 76.931638]
[105/231] Geocoding: Block P South city 1
    Coordinates: None
[106/231] Geocoding: Ansal Plaza
    Coordinates: [28.511342, 77.0417054]
[107/231] Geocoding: Heritage City
    Coordinates: [28.4817226, 77.0784621]
[108/231] Geocoding: Sushant Lok
    Coordinates: [28.4706634, 77.0798127]
[109/231] Geocoding: Sushant Lok 3 Extension
    Coordinates: None
[110/231] Geocoding: Chakkarpur
    Coordinates: [28.4715202, 77.0913233]
[111/231] Geocoding: B Block Sushant Lok Phase 1
    Coordinates: None
[112/231] Geocoding: Sector 114 Gurgaon
    Coordinates: [28.5318781, 77.0117794]
[113/231] Geocoding: New Palam Vihar Phase 1
    Coordinates: None
[114/231] Geocoding: Sector 22 Gurgaon
    Coordinates: [28.5020206, 77.0707766]
[115/231] Geocoding: Sector 95 Gurgaon
    Coordinates: [28.4149443, 76.9114892]
[116/231] Geocoding: C Block Mayfield Garden
    Coordinates: [28.4225252, 77.0612084]
[117/231] Geocoding: C Block Pocket I Mayfield Garden
    Coordinates: None
[118/231] Geocoding: Suncity
    Coordinates: [28.4331217, 77.1055195]
[119/231] Geocoding: Sector 76 Gurgaon
    Coordinates: [28.3910112, 76.9900243]
[120/231] Geocoding: Sector 4 Gurgaon
    Coordinates: [28.4682659, 77.0325424]
[121/231] Geocoding: rapid metro 55-56
    Coordinates: None
[122/231] Geocoding: sector 58 Gurgaon
    Coordinates: [28.4160012, 77.1085564]
[123/231] Geocoding: Sector 15 Part 2
    Coordinates: [28.4534919, 77.0411056]
[124/231] Geocoding: Valley View Estate
    Coordinates: [28.4358878, 77.1365212]
[125/231] Geocoding: Sector 33 Gurgaon
    Coordinates: [28.4384785, 77.0251655]
[126/231] Geocoding: Maruti Kunj
    Coordinates: [28.3593202, 77.077969]
[127/231] Geocoding: Sector 1 Imt Manesar
    Coordinates: [28.3671851, 76.920669]
[128/231] Geocoding: Sector 34 Gurgaon
    Coordinates: [28.4280033, 77.0115678]
[129/231] Geocoding: Mayfield Garden
    Coordinates: [28.4227493, 77.0705636]
[130/231] Geocoding: Sector 73 Gurgaon
    Coordinates: [28.4088081, 77.0161691]
[131/231] Geocoding: Shyam Kunj
    Coordinates: [28.3610143, 77.075964]
[132/231] Geocoding: Sector 91 Gurgaon
    Coordinates: [28.4007588, 76.9210802]
[133/231] Geocoding: Sohna Road
    Coordinates: [28.3999199, 77.0451273]
[134/231] Geocoding: Vigyan Vihar
    Coordinates: None
[135/231] Geocoding: Sector 78 Gurgaon
    Coordinates: [28.3725283, 76.9702955]
[136/231] Geocoding: Sector 30 Gurgaon
    Coordinates: [28.4618719, 77.05688]
[137/231] Geocoding: Block T New Palam Vihar Phase 2
    Coordinates: None
[138/231] Geocoding: Block D, New Palam Vihar
    Coordinates: None
[139/231] Geocoding: Block D New Palam Vihar Phase 2
    Coordinates: None
[140/231] Geocoding: A Block Sushant Lok Phase - 3
    Coordinates: None
[141/231] Geocoding: sector 47 , sector 51
    Coordinates: None
[142/231] Geocoding: Block M South City 1
    Coordinates: [28.4538821, 77.0626859]
[143/231] Geocoding: Pocket I Nirvana Country
    Coordinates: None
[144/231] Geocoding: DLF CITY
    Coordinates: [28.483901, 77.0846097]
[145/231] Geocoding: Sector 5 Gurgaon
    Coordinates: [28.4550311, 77.070171]
[146/231] Geocoding: Golf Course Ext Road
    Coordinates: [28.4076552, 77.0615981]
[147/231] Geocoding: Bhondsi
    Coordinates: [28.3504798, 77.0618737]
[148/231] Geocoding: Greenwood City
    Coordinates: [28.4449095, 77.0611408]
[149/231] Geocoding: Sector 10A Gurgaon
    Coordinates: [28.4445813, 77.0060231]
[150/231] Geocoding: New golf course ext road
    Coordinates: [28.3950687, 77.0314323]
[151/231] Geocoding: Sector 39 Gurgaon
    Coordinates: [28.4433686, 77.0552345]
[152/231] Geocoding: Sector 77 Gurgaon
    Coordinates: [28.3832337, 76.982557]
[153/231] Geocoding: Block K South City 1
    Coordinates: [28.4521251, 77.0631645]
[154/231] Geocoding: Subhash Nagar
    Coordinates: None
[155/231] Geocoding: Sector 95A Gurgaon
    Coordinates: [28.3898758, 77.0762672]
[156/231] Geocoding: New Colony
    Coordinates: [28.4662572, 77.0142654]
[157/231] Geocoding: Sector 15 Gurgaon
    Coordinates: [28.5286649, 77.0250282]
[158/231] Geocoding: Sector 40 Gurgaon
    Coordinates: [28.4433686, 77.0552345]
[159/231] Geocoding: Rattan Garden
    Coordinates: None
[160/231] Geocoding: Block M DLF phase 2
    Coordinates: None
[161/231] Geocoding: Surat Nagar 1
    Coordinates: [28.4835461, 77.0023716]
[162/231] Geocoding: Udyog Vihar Industrial Area Phase 6
    Coordinates: None
[163/231] Geocoding: Laxman Vihar
    Coordinates: None
[164/231] Geocoding: Dharam Colony
    Coordinates: None
[165/231] Geocoding: Block-A, DLF City Phase 1
    Coordinates: None
[166/231] Geocoding: Sector 7 Extension
    Coordinates: [28.4967161, 77.0274408]
[167/231] Geocoding: Sector 9 Gurgaon
    Coordinates: [28.3840986, 76.8861337]
[168/231] Geocoding: Sector 23A Gurgaon
    Coordinates: [28.5056942, 77.0463022]
[169/231] Geocoding: Block N, Mayfield garden
    Coordinates: [28.4263326, 77.0619263]
[170/231] Geocoding: Sector 38 Gurgaon
    Coordinates: [28.4351423, 77.0403538]
[171/231] Geocoding: Block C Sushant Lok Phase - 3
    Coordinates: [28.4545693, 77.0826249]
[172/231] Geocoding: Block C Ardee City
    Coordinates: None
[173/231] Geocoding: Westerlies
    Coordinates: None
[174/231] Geocoding: Sector 2 Gurgaon
    Coordinates: [28.507267, 77.0313266]
[175/231] Geocoding: Block F, Sushant Lok Phase - 2
    Coordinates: None
[176/231] Geocoding: Sector 41 Gurgaon
    Coordinates: [28.4433686, 77.0552345]
[177/231] Geocoding: sector 28 , Golf course road
    Coordinates: [28.4495292, 77.0995152]
[178/231] Geocoding: Southern Peripheral Road
    Coordinates: [28.4021644, 77.0382675]
[179/231] Geocoding: South City
    Coordinates: [28.4597391, 77.0612091]
[180/231] Geocoding: Rajiv Chowk
    Coordinates: [28.4456277, 77.0337985]
[181/231] Geocoding: Block B Sector 2 Palam Vihar
    Coordinates: [28.484711, 77.0273173]
[182/231] Geocoding: Sector 17 Gurgaon
    Coordinates: [28.4758035, 77.0607773]
[183/231] Geocoding: Rosewood City
    Coordinates: [28.4102341, 77.0544854]
[184/231] Geocoding: Samaspur
    Coordinates: [28.426803, 77.0659832]
[185/231] Geocoding: Saraswati Vihar
    Coordinates: [28.4772236, 77.0832762]
[186/231] Geocoding: Kadarpur
    Coordinates: [28.3918989, 77.0609767]
[187/231] Geocoding: D Block Sushant Lok Phase 1
    Coordinates: None
[188/231] Geocoding: sector 83 vatika floor
    Coordinates: None
[189/231] Geocoding: Pataudi Road
    Coordinates: [28.347879, 76.7522376]
[190/231] Geocoding: New Gurgaon
    Coordinates: [28.4671681, 77.018953]
[191/231] Geocoding: Sai Kunj
    Coordinates: [28.3673281, 77.0782229]
[192/231] Geocoding: Sector 21 Gurgaon
    Coordinates: [28.5143629, 77.0730087]
[193/231] Geocoding: Sector 9A Gurgaon
    Coordinates: [28.4690266, 76.9962811]
[194/231] Geocoding: Ambience
    Coordinates: [28.5007796, 77.102441]
[195/231] Geocoding: Sector 17A Gurgaon
    Coordinates: [28.5175247, 77.0425692]
[196/231] Geocoding: Sector 17B Gurgaon
    Coordinates: [28.407697, 77.0823781]
[197/231] Geocoding: Sector 7 Gurgaon
    Coordinates: [28.4671681, 77.018953]
[198/231] Geocoding: Ashok Vihar Phase 1
    Coordinates: [28.4967161, 77.0274408]
[199/231] Geocoding: Sector-5 Sohna
    Coordinates: [28.3241636, 77.0848644]
[200/231] Geocoding: Bissar
    Coordinates: None
[201/231] Geocoding: Sec 90
    Coordinates: [28.4069974, 76.9365562]
[202/231] Geocoding: Block E DLF City Phase 1
    Coordinates: None
[203/231] Geocoding: sector 62emaar uarban oasis
    Coordinates: None
[204/231] Geocoding: Farrukh Nagar
    Coordinates: [28.4449338, 76.8194023]
[205/231] Geocoding: Sector 80 Gurgaon
    Coordinates: [28.3702173, 76.9611159]
[206/231] Geocoding: Dayanand Colony
    Coordinates: [28.4728756, 77.0220042]
[207/231] Geocoding: Phase 2 Sushant Lok 3
    Coordinates: None
[208/231] Geocoding: Block C Sector 17 Gurgaon
    Coordinates: [28.5063278, 77.0289658]
[209/231] Geocoding: Sector 17C Gurgaon
    Coordinates: [28.407697, 77.0823781]
[210/231] Geocoding: Cyber City
    Coordinates: [28.4980703, 77.0892567]
[211/231] Geocoding: Patel Nagar
    Coordinates: [28.4657746, 77.0391986]
[212/231] Geocoding: Ramgarh
    Coordinates: [28.3940897, 77.0658684]
[213/231] Geocoding: Sector 64 Gurgaon
    Coordinates: [28.3898758, 77.0762672]
[214/231] Geocoding: Sector 9A Sector 9 Gurgaon
    Coordinates: [28.4690266, 76.9962811]
[215/231] Geocoding: Subhash Chowk
    Coordinates: [28.4277156, 77.0371069]
[216/231] Geocoding: Jharsa
    Coordinates: [28.4445323, 77.0491372]
[217/231] Geocoding: Civil Lines
    Coordinates: [28.4616851, 77.0339023]
[218/231] Geocoding: Block C Greenwood City
    Coordinates: None
[219/231] Geocoding: Sector 10 Gurgaon
    Coordinates: [28.4445813, 77.0060231]
[220/231] Geocoding: Sector 22B Gurgaon
    Coordinates: [28.5175247, 77.0425692]
[221/231] Geocoding: Badshahpur
    Coordinates: [28.3932757, 77.0484201]
[222/231] Geocoding: C block Sector 43 Gurgaon
    Coordinates: [28.4545693, 77.0826249]
[223/231] Geocoding: Shivpuri
    Coordinates: None
[224/231] Geocoding: Gurgaon
    Coordinates: [28.4890874, 77.0111572]
[225/231] Geocoding: Dwarka Expressway Gurgaon
    Coordinates: [28.4972279, 77.004102]
[226/231] Geocoding: Palam Vihar Extension
    Coordinates: [28.5007712, 77.0398992]
[227/231] Geocoding: Valley View Estate gwal Pahari
    Coordinates: None
[228/231] Geocoding: Sector 83 New Gurgaon
    Coordinates: [28.467026, 77.0136083]
[229/231] Geocoding: Jyoti Park
    Coordinates: None
[230/231] Geocoding: Sector - 33, Sohna, Gurgaon
    Coordinates: [28.3241636, 77.0848644]
[231/231] Geocoding: Sector 1A IMT Manesar
    Coordinates: [28.3671851, 76.920669]

Geocoding completed!
Total localities: 231
Cached results: 231
Successful results: 192
Unsuccessful lookups: 39

In [22]:
# Convert successful cached coordinates into a DataFrame

coords = pd.DataFrame(
    [
        (locality, values[0], values[1])
        for locality, values in cache.items()
        if values is not None
    ],
    columns=["LOCALITY", "latitude", "longitude"]
)

# Ensure one row per locality
coords = coords.drop_duplicates(subset=["LOCALITY"])

# Remove previously merged coordinate columns if present
df = df.drop(
    columns=["latitude", "longitude"],
    errors="ignore"
)

# Merge coordinates with the original property records
df = df.merge(
    coords,
    on="LOCALITY",
    how="left",
    validate="many_to_one"
)

print("Total property records:", len(df))
print("Unique localities:", df["LOCALITY"].nunique())
print("Localities with coordinates:", coords["LOCALITY"].nunique())
print("Properties without coordinates:", df["latitude"].isna().sum())

display(df[["LOCALITY", "latitude", "longitude"]].head(10))

Total property records: 10704
Unique localities: 231
Localities with coordinates: 192
Properties without coordinates: 383

             LOCALITY   latitude  longitude
0   Sector 84 Gurgaon  28.403547  76.967789
1   Sector 81 Gurgaon  28.387365  76.947583
2   Sector 66 Gurgaon  28.397429  77.053882
3  Sector 112 Gurgaon  28.520340  77.018861
4  Sector 104 Gurgaon  28.479532  76.993720
5  Sector 104 Gurgaon  28.479532  76.993720
6  Sector 104 Gurgaon  28.479532  76.993720
7   Sector 74 Gurgaon  28.411008  77.010121
8  Sector 108 Gurgaon  28.512899  76.982361
9  Sector 102 Gurgaon  28.475487  76.971175

In [23]:
from pathlib import Path

project_root = Path("..")
processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

output_path = processed_dir / "housing_with_coordinates.csv"

df.to_csv(output_path, index=False)

print("Dataset saved successfully!")
print("Location:", output_path.resolve())

Dataset saved successfully!
Location: D:\real-estate-price-prediction\data\processed\housing_with_coordinates.csv

In [24]:
# Bounding-box validation for Gurgaon, Haryana

LAT_MIN, LAT_MAX = 28.30, 28.60
LON_MIN, LON_MAX = 76.85, 77.20

# Identify coordinates outside the expected bounds
bad = df[
    df["latitude"].notna()
    & df["longitude"].notna()
    & (
        (df["latitude"] < LAT_MIN)
        | (df["latitude"] > LAT_MAX)
        | (df["longitude"] < LON_MIN)
        | (df["longitude"] > LON_MAX)
    )
]

print("Total property records:", len(df))
print("Rows with coordinates:", df["latitude"].notna().sum())
print("Out-of-bounds rows:", len(bad))

print("\nLocalities with out-of-bounds coordinates:")

if not bad.empty:
    print(
        bad[["LOCALITY", "latitude", "longitude"]]
        .drop_duplicates()
        .to_string(index=False)
    )
else:
    print("None found.")

Total property records: 10704
Rows with coordinates: 10321
Out-of-bounds rows: 2

Localities with out-of-bounds coordinates:
     LOCALITY  latitude  longitude
 Pataudi Road 28.347879  76.752238
Farrukh Nagar 28.444934  76.819402

In [25]:
# Part G.1: Bounding-box validation for Gurgaon

LAT_MIN, LAT_MAX = 28.30, 28.60
LON_MIN, LON_MAX = 76.85, 77.20

# Only validate rows with coordinates
has_coords = df["latitude"].notna() & df["longitude"].notna()

# Find coordinates outside the approximate bounds
bad = df[
    has_coords
    & (
        (df["latitude"] < LAT_MIN)
        | (df["latitude"] > LAT_MAX)
        | (df["longitude"] < LON_MIN)
        | (df["longitude"] > LON_MAX)
    )
]

print("Total property records:", len(df))
print("Records with coordinates:", has_coords.sum())
print("Records without coordinates:", (~has_coords).sum())
print("Out-of-bounds rows:", len(bad))

print("\nPotentially incorrect locality coordinates:")

if not bad.empty:
    print(
        bad[["LOCALITY", "latitude", "longitude"]]
        .drop_duplicates()
        .to_string(index=False)
    )
else:
    print("No coordinates outside the approximate bounds.")

Total property records: 10704
Records with coordinates: 10321
Records without coordinates: 383
Out-of-bounds rows: 2

Potentially incorrect locality coordinates:
     LOCALITY  latitude  longitude
 Pataudi Road 28.347879  76.752238
Farrukh Nagar 28.444934  76.819402

In [26]:
import folium
from pathlib import Path

# Keep rows with valid coordinate values
map_df = df.dropna(subset=["latitude", "longitude"]).copy()

# Use one marker per locality
map_df = map_df.drop_duplicates(subset=["LOCALITY"])

# Create the map
if not map_df.empty:

    center_lat = map_df["latitude"].mean()
    center_lon = map_df["longitude"].mean()

    m = folium.Map(
        location=[center_lat, center_lon],
        zoom_start=11
    )

    # Draw the approximate Gurgaon bounding box
    folium.Rectangle(
        bounds=[
            [LAT_MIN, LON_MIN],
            [LAT_MAX, LON_MAX]
        ],
        color="red",
        fill=False,
        tooltip="Approximate Gurgaon screening bounds"
    ).add_to(m)

    # Add a marker for each locality
    for _, row in map_df.iterrows():

        is_outside = (
            row["latitude"] < LAT_MIN
            or row["latitude"] > LAT_MAX
            or row["longitude"] < LON_MIN
            or row["longitude"] > LON_MAX
        )

        folium.CircleMarker(
            location=[
                row["latitude"],
                row["longitude"]
            ],
            radius=4,
            popup=(
                f"Locality: {row['LOCALITY']}<br>"
                f"Latitude: {row['latitude']}<br>"
                f"Longitude: {row['longitude']}<br>"
                f"Outside bounds: {is_outside}"
            ),
            color="red" if is_outside else "blue",
            fill=True
        ).add_to(m)

    # Save the HTML file
    project_root = Path("..")
    reports_dir = project_root / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    map_path = reports_dir / "locality_map.html"
    m.save(str(map_path))

    print("Interactive map saved successfully!")
    print("Map location:", map_path.resolve())
    print("Localities displayed:", len(map_df))

else:
    print("No valid coordinates available to plot.")

Interactive map saved successfully!
Map location: D:\real-estate-price-prediction\reports\locality_map.html
Localities displayed: 189

In [27]:
from pathlib import Path

# Create the raw data directory if needed
project_root = Path("..")
raw_dir = project_root / "data" / "raw"
raw_dir.mkdir(parents=True, exist_ok=True)

# Save the geocoded dataset
output_path = raw_dir / "housing_with_coords.csv"

df.to_csv(output_path, index=False)

print("Dataset saved successfully!")
print("File:", output_path.resolve())
print("Rows:", len(df))
print("Columns:", len(df.columns))
print(
    "Properties without coordinates:",
    df["latitude"].isna().sum()
)

Dataset saved successfully!
File: D:\real-estate-price-prediction\data\raw\housing_with_coords.csv
Rows: 10704
Columns: 69
Properties without coordinates: 383